###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    server:
      image: nginx:alpine
      container_name: serverquantox
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8977:80"
      depends_on: 
       - php-fpm
      networks: 
        - network

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpquantox
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      networks: 
        - network

networks:
    network:
        driver: bridge